### ISSUE TITLE
Version question about Installing 

### ISSUE THREAD

**Issue by wJDKnight** [zcang/SpaOTsc#12]
What the version of the python you used?
In the requirements.txt, you used the numpy==1.22.0 supported by py3.8-py3.10 but the scipy==1.3.0 supported by py3.6/py3.7.

**Comment by zcang** [comment]
I used Python3.7. The original NumPy version was 1.16.4 but was bumped to 1.22 suggested by GitHub dependabot due to a potential security issue.
