### ISSUE TITLE
Dissimilarity matrices

### ISSUE THREAD

**Issue by camerongw** [zcang/SpaOTsc#2]
Hi, thanks for sharing this tool with everyone. It looks pretty promising and I'm keen to give it a go with some slide-seq data.
Just wondering how you generated the distance and dissimilarity matrices?
I know that the full documentation of your methods is available but it's quite a large file so I think it'll be easier to just ask here.

Cheers

**Comment by zcang** [comment]
Hi, please see this [closed issue](https://github.com/zcang/SpaOTsc/issues/1) with the same question.
Thanks.
