### ISSUE TITLE
A question about example data

### ISSUE THREAD

**Issue by YeehanXiao** [zcang/SpaOTsc#3]
May I know how to get the input data at the first beginning? I mean, the pipeline starts with "dm_is.txt", "dm_is_binarized.txt",etc. Could you give me more details about getting this format of data from other spatial data? How could I binarize the expression matrix

**Comment by zcang** [comment]
Hi, this particular data was directly downloaded from this [Dream challenge](https://www.synapse.org/#!Synapse:syn15665609/wiki/582909) associated with this [paper](https://science.sciencemag.org/content/358/6360/194/tab-figures-data) which was already binarized by the authors/challenge organizers. There are different packages for binarizing/discretizing custom data, for example, the binarization utility [here](https://github.com/rajewsky-lab/distmap) or more general-purpose ones, e.g., Gaussian mixture. You can also use unbinarized expression with correlation coefficients, e.g. the ranking based ones.
