### ISSUE TITLE
Noncontinuous positions in spatial transcriptomics

### ISSUE THREAD

**Issue by rlittman16** [zcang/SpaOTsc#5]
Hello! 

I'm interested in using your tool to map my scRNAseq data to spatial transcriptomics in the same tissue. The positions imaged are not continuous, and are from different parts of the tissue. How would you proceed with this?

Thanks!

**Comment by crichgriffin** [comment]
I have the same question!

**Comment by zcang** [comment]
Sorry for replying so late. I believe the integration should still work if there is a significant overlapping of scRNA-seq and spatial data. Just that the parameter "alpha" in the function "transport_plan" should be set to 0.
