### ISSUE TITLE
what is the "sequence" in the function "visualize_cells"

### ISSUE THREAD

**Issue by qianxu05172019** [zcang/SpaOTsc#8]
Could you explain me what is the meaning of  "sequence" in the function "visualize_cells"?

https://github.com/zcang/SpaOTsc/blob/206f91503a1457605e3a04c39a8d48b42907f42d/spaotsc/SpaOTsc.py#L1388

**Comment by zcang** [comment]
Hello, sorry for the confusion. I meant the expression data.
